#!/usr/bin/env python
# coding: utf-8

# # Convert the outFile from HISAT2 to table in Excel
# 
# The script converts the output file generated by HISAT2 into a structured table format and writes the results to an Excel file. It parses the input file, extracts relevant data sections, and creates a DataFrame using pandas. The final DataFrame is then saved as an Excel file named output_file.xlsx. Additionally, the script includes comments for clarity and provides instructions on how to merge files from HISAT and install the necessary pandas library.

# In[17]:


# To merge the file from HISAT use
#tail -n +1 *.err > concatenated_filename_output.txt


# In[12]:


import pandas as pd

# Read input file and split into individual sections
with open('concatenated_Ticks_output.txt') as f:
    data = f.read().split('== ')

# Remove empty first item
data = data[1:]

# Extract data from each section
results = []
for section in data:
    lines = section.strip().split('\n')
    filename = lines[0].strip()
    reads = lines[1].split('reads')[0].strip()
    overall_alignment_rate = lines[-1].split()[0].strip()
    results.append((filename, reads, overall_alignment_rate))

# Convert results to DataFrame and write to Excel
df = pd.DataFrame(results, columns=['Filename', 'Reads', 'Overall Alignment Rate'])
df.to_excel('output_Ticks_Test.xlsx', index=False)


# In[13]:


# Read the Excel file generated by the script
df = pd.read_excel('output_Ticks_Test.xlsx')
print(df)


# Name: HISAT2_Output_to_Excel_Converter.py
# Description: The script converts the output file generated by HISAT2 into a structured table format and writes the results to an Excel file. It parses the input file, extracts relevant data sections, and creates a DataFrame using pandas. The final DataFrame is then saved as an Excel file named output_file.xlsx. Additionally, the script includes comments for clarity and provides instructions on how to merge files from HISAT and install the necessary pandas library.
# Author: Zaide Montes
#  Institution: Lund University, Pheromone group to run in Rackham, uppmax
# #Contact email: zk.montes10@gmail.com
# #Date: Implemented on Nov 7, 2022

# In[ ]:




